---
layout: page
title: Fundamental Models and Concepts in Ecology
excerpt: Fundamentals
execute:
  freeze: true  # never re-render during project render
engine: knitr 
sidebar: false
toc: true
toc-location: left
toc-title: Topics
#css: tocstyles.css
format: html
#server: shiny

#html:
#    toc: true
#    toc-title: "Contents"
#    toc-depth: 1
#    number-sections: true
#    toc-location: left
#    css: tocstyles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
#library(webexercises)
library(ggplot2)
```

# Introduction

<details>

<summary>Course motivation</summary>

</details>

# Density-independent growth

<details>

<summary>How do populations grow?</summary>

## Growth in variable environments
::: {.webex-check .webex-box}
```{r, results='asis', echo = FALSE}
opts <-   c(answer="Population A","Population B")
Question <- 
"Consider two populations, each starting with one individual. These populations live in a seasonal environment, with a “good” season and a “bad” season occuring every year. A biological example may be a 'wet' and 'dry' season. Population A is unaffected by seasons and grows at a constant rate λ = 2 each season – thus, each season, each individual in population A produces 2 offspring per death. Population B grows differently depending on the season, where λ = 7  each good season and λ = 0.5 each bad season. Which population will grow faster? Justify your answer before checking."

cat(Question, longmcq(opts))
```
:::


</details>

# Density-dependent growth

<details>

<summary>What limits population growth?</summary>

</details>

---
